services:
  volumes-init:
    build: .
    restart: no
    entrypoint: /bin/sh -c 'chown -R ubuntu:ubuntu /home/ubuntu'
    volumes:
      - 'events:/home/ubuntu/events:rw'
      - 'wallets:/home/ubuntu/wallets:rw'

  event-management:
    build: .
    restart: unless-stopped
    depends_on:
      - volumes-init
    user: 'ubuntu:ubuntu'
    command: 'socat TCP-LISTEN:1338,fork,reuseaddr EXEC:/home/ubuntu/dist/event-management'
    ports:
      - '1338:1338'
    volumes:
      - './dist:/home/ubuntu/dist:ro'
      - 'events:/home/ubuntu/events:rw'

  wallet:
    build: .
    restart: unless-stopped
    depends_on:
      - volumes-init
    user: 'ubuntu:ubuntu'
    command: 'socat TCP-LISTEN:1337,fork,reuseaddr EXEC:/home/ubuntu/dist/wallet'
    ports:
      - '1337:1337'
    volumes:
      - './dist:/home/ubuntu/dist:ro'
      - 'events:/home/ubuntu/events:ro'
      - 'wallets:/home/ubuntu/wallets:rw'

volumes:
  events:
    driver: local
  wallets:
    driver: local