version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    volumes:
      - db_volume:/var/lib/mysql

  app:
    build: backend
    container_name: app
    restart: always
    environment:
      DBHOST: db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/usr/share/nginx/html

volumes:
  db_volume: