services:
  cooking-nonna:
    build: service
    restart: unless-stopped
    ports:
      - '2222:2222'
    volumes:
      - './service/build:/chall:ro'
      - './data:/data'

  cleaner:
    build: cleaner
    restart: unless-stopped
    volumes:
      - "./data:/tmp/data"
    depends_on:
      - cooking-nonna
